### ISSUE TITLE
0.03版本 exe文件无法运行

### ISSUE THREAD

**Issue by rainlighter** [webscrapingproject/icourse-downloader#2]
我下载了，windows平台的两个exe文件，
icourse-downloader_0.0.3_Windows_i386.tar.gz
icourse-downloader_0.0.3_Windows_x86_64.tar.gz

解压后：
1.双击运行没有效果。
2.右键管理员权限运行也没有界面出现。

请问要怎么操作啊?

**Comment by rainlighter** [comment]
D:\Program Files\icourse>icourse-downloader.exe https://www.icourse163.org/learn/SDU-1001907001?tid=1003113029
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
icourse/parser.GetCsrfKey(...)
        /home/runner/work/icourse-downloader/icourse-downloader/parser/icourse163.go:163
icourse/parser.parseIcourse163VideoFile(0xc0003020f3, 0xa, 0x0, 0x0, 0xc0004e83c0, 0x1)
        /home/runner/work/icourse-downloader/icourse-downloader/parser/icourse163.go:110 +0x53d
icourse/parser.parseIcourse163Video(0xc0003020f3, 0xa, 0x0, 0x0, 0x1, 0x1, 0xa)
        /home/runner/work/icourse-downloader/icourse-downloader/parser/icourse163.go:120 +0x54
icourse/parser.ExtractIcourse163Res(0xc000300000, 0x3a8bb, 0x0, 0x0, 0xc0003f4000, 0x1, 0xa, 0x6, 0x0, 0x0, ...)
        /home/runner/work/icourse-downloader/icourse-downloader/parser/icourse163.go:55 +0x381
icourse/parser.DownloadIcourse163(0xc000010200, 0x3e, 0x71d4b0, 0x3, 0x0, 0x0, 0x3)
        /home/runner/work/icourse-downloader/icourse-downloader/parser/icourse163.go:178 +0x15d
main.download(0xc000010200, 0x3e, 0xc000010200)
        /home/runner/work/icourse-downloader/icourse-downloader/main.go:37 +0x215
main.main()
        /home/runner/work/icourse-downloader/icourse-downloader/main.go:70 +0x122
